"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect,useRef,useState } from "react";

const HIDDEN_KEY="brandflow-assistant-hidden";
type Context={mediaCount:number|null;scheduledCount:number|null;latestAdvisor:null|{platform:string;analysis?:{overallScore?:number;suggestedCampaignObjective?:string}};cashflow:null|{income:number;expense:number;net:number}};

export function ExecutiveAssistant(){
 const pathname=usePathname();const[open,setOpen]=useState(false);const[hidden,setHidden]=useState(false);const[notice,setNotice]=useState(true);const[context,setContext]=useState<Context|null>(null);const holdTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{const timer=window.setTimeout(()=>setHidden(localStorage.getItem(HIDDEN_KEY)==="1"),0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{if(!open)return;let active=true;fetch("/api/assistant/context").then(r=>r.ok?r.json():null).then(j=>{if(active&&j?.data)setContext(j.data)}).catch(()=>undefined);return()=>{active=false}},[open,pathname]);
 if(pathname.startsWith("/sign-in")||pathname.startsWith("/sign-up"))return null;
 function startHold(){holdTimer.current=setTimeout(()=>{localStorage.setItem(HIDDEN_KEY,"1");setHidden(true);setOpen(false)},850)}
 function stopHold(){if(holdTimer.current)clearTimeout(holdTimer.current);holdTimer.current=null}
 if(hidden)return <button type="button" onClick={()=>{localStorage.removeItem(HIDDEN_KEY);setHidden(false)}} className="fixed bottom-4 right-4 z-[80] rounded-full border border-violet-400/30 bg-[#090a14]/90 px-3 py-2 text-xs font-bold text-violet-200 shadow-2xl backdrop-blur-xl">AI Asistanı Göster</button>;
 const score=context?.latestAdvisor?.analysis?.overallScore;const net=context?.cashflow?.net;
 return <div className="fixed bottom-5 right-5 z-[80] flex items-end gap-3">{(open||notice)&&<div className="mb-3 w-[320px] overflow-hidden rounded-2xl border border-violet-400/20 bg-[#080914]/94 shadow-[0_24px_80px_rgba(30,10,70,.52)] backdrop-blur-2xl"><div className="border-b border-white/10 bg-gradient-to-r from-violet-600/18 to-indigo-500/5 px-4 py-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-300">BrandFlow AI</p><p className="mt-1 text-sm font-bold text-white">İş ortağın hazır.</p></div><button onClick={()=>{setNotice(false);setOpen(false)}} className="text-zinc-500 transition hover:text-white" aria-label="Kapat">×</button></div></div><div className="space-y-3 p-4"><p className="text-sm leading-6 text-zinc-300">Bulunduğun sayfayı ve BrandFlow iç verilerini birlikte değerlendirip sana uygulanabilir sonraki adımı gösterebilirim.</p>{open&&<div className="grid grid-cols-3 gap-2"><div className="rounded-xl bg-white/[.04] p-2 text-center"><p className="text-[10px] text-zinc-500">Medya</p><p className="mt-1 text-sm font-black text-white">{context?.mediaCount??"—"}</p></div><div className="rounded-xl bg-white/[.04] p-2 text-center"><p className="text-[10px] text-zinc-500">Plan</p><p className="mt-1 text-sm font-black text-white">{context?.scheduledCount??"—"}</p></div><div className="rounded-xl bg-white/[.04] p-2 text-center"><p className="text-[10px] text-zinc-500">Skor</p><p className="mt-1 text-sm font-black text-white">{score??"—"}</p></div></div>}{open&&typeof net==="number"&&<div className={`rounded-xl border px-3 py-2 text-xs ${net>=0?"border-emerald-400/15 bg-emerald-400/[.06] text-emerald-200":"border-amber-400/15 bg-amber-400/[.06] text-amber-200"}`}>Hesap akışı neti: {new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(net)}</div>}<div className="grid gap-2"><Link href="/company-doctor" className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm font-semibold text-white transition hover:border-violet-400/35 hover:bg-violet-500/10">Şirketimi analiz et</Link><Link href="/opportunities" className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm font-semibold text-white transition hover:border-violet-400/35 hover:bg-violet-500/10">Yeni fırsatları göster</Link><Link href="/create" className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm font-semibold text-white transition hover:border-violet-400/35 hover:bg-violet-500/10">Bugün ne paylaşmalıyım?</Link></div><p className="text-[11px] text-zinc-500">Asistanı yaklaşık 1 saniye basılı tutarak gizleyebilirsin.</p></div></div>}
 <button type="button" onClick={()=>{setOpen(v=>!v);setNotice(false)}} onPointerDown={startHold} onPointerUp={stopHold} onPointerLeave={stopHold} onPointerCancel={stopHold} className="group relative h-[104px] w-[82px] select-none border-0 bg-transparent transition duration-300 hover:-translate-y-1" aria-label="BrandFlow AI Asistan">
  <span className="absolute bottom-0 left-1/2 h-[10px] w-[68px] -translate-x-1/2 rounded-full bg-violet-600/50 blur-[7px] transition group-hover:bg-violet-500/70"/>
  <span className="absolute bottom-[3px] left-1/2 h-[5px] w-[58px] -translate-x-1/2 rounded-full border border-violet-400/60 bg-[#170d31] shadow-[0_0_18px_rgba(139,92,246,.85)]"/>
  <span className="absolute left-1/2 top-[4px] h-[42px] w-[52px] -translate-x-1/2 rounded-[45%_45%_40%_40%] border border-zinc-300/35 bg-gradient-to-br from-zinc-200 via-zinc-500 to-zinc-950 shadow-[inset_5px_4px_8px_rgba(255,255,255,.2),inset_-7px_-8px_12px_rgba(0,0,0,.75),0_8px_18px_rgba(0,0,0,.45)]"/>
  <span className="absolute left-1/2 top-[10px] h-[29px] w-[43px] -translate-x-1/2 rounded-[44%] border border-white/10 bg-gradient-to-b from-[#171823] to-[#020207] shadow-[inset_0_4px_8px_rgba(255,255,255,.04)]"/>
  <span className="absolute left-[26px] top-[22px] h-[7px] w-[7px] rounded-full bg-violet-500 shadow-[0_0_11px_3px_rgba(139,92,246,.9)]"/><span className="absolute right-[26px] top-[22px] h-[7px] w-[7px] rounded-full bg-violet-500 shadow-[0_0_11px_3px_rgba(139,92,246,.9)]"/>
  <span className="absolute left-[12px] top-[18px] h-[18px] w-[8px] rounded-full border border-zinc-300/30 bg-gradient-to-r from-zinc-800 to-zinc-400"/><span className="absolute right-[12px] top-[18px] h-[18px] w-[8px] rounded-full border border-zinc-300/30 bg-gradient-to-l from-zinc-800 to-zinc-400"/>
  <span className="absolute bottom-[10px] left-1/2 h-[55px] w-[54px] -translate-x-1/2 rounded-[15px_15px_11px_11px] border border-white/10 bg-gradient-to-br from-[#24252d] via-[#0c0d12] to-black shadow-[inset_5px_0_8px_rgba(255,255,255,.05),0_10px_20px_rgba(0,0,0,.55)]"/>
  <span className="absolute bottom-[10px] left-[8px] h-[39px] w-[13px] -rotate-[10deg] rounded-full border border-white/10 bg-gradient-to-r from-black to-zinc-700"/><span className="absolute bottom-[10px] right-[8px] h-[39px] w-[13px] rotate-[10deg] rounded-full border border-white/10 bg-gradient-to-l from-black to-zinc-700"/>
  <span className="absolute bottom-[45px] left-1/2 h-[12px] w-[21px] -translate-x-1/2 bg-white [clip-path:polygon(0_0,50%_100%,100%_0)]"/>
  <span className="absolute bottom-[27px] left-1/2 h-[28px] w-[8px] -translate-x-1/2 bg-gradient-to-b from-violet-400 to-violet-800 [clip-path:polygon(50%_0,100%_18%,70%_100%,30%_100%,0_18%)] shadow-[0_0_9px_rgba(139,92,246,.5)]"/>
  <span className="absolute -right-1 top-0 h-3 w-3 rounded-full border-2 border-[#080914] bg-emerald-400 shadow-[0_0_12px_#34d399]"/>
 </button></div>
}
