"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect,useRef,useState } from "react";

const HIDDEN_KEY="brandflow-assistant-hidden";
type Context={mediaCount:number|null;scheduledCount:number|null;latestAdvisor:null|{platform:string;analysis?:{overallScore?:number;suggestedCampaignObjective?:string}};cashflow:null|{income:number;expense:number;net:number}};
function initialHidden(){return typeof window!=="undefined"&&localStorage.getItem(HIDDEN_KEY)==="1"}

export function ExecutiveAssistant(){
 const pathname=usePathname();const[open,setOpen]=useState(false);const[hidden,setHidden]=useState(initialHidden);const[notice,setNotice]=useState(true);const[context,setContext]=useState<Context|null>(null);const holdTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(!open)return;let active=true;fetch("/api/assistant/context").then(r=>r.ok?r.json():null).then(j=>{if(active&&j?.data)setContext(j.data)}).catch(()=>undefined);return()=>{active=false}},[open,pathname]);
 if(pathname.startsWith("/sign-in")||pathname.startsWith("/sign-up"))return null;
 function startHold(){holdTimer.current=setTimeout(()=>{localStorage.setItem(HIDDEN_KEY,"1");setHidden(true);setOpen(false)},850)}
 function stopHold(){if(holdTimer.current)clearTimeout(holdTimer.current);holdTimer.current=null}
 if(hidden)return <button type="button" onClick={()=>{localStorage.removeItem(HIDDEN_KEY);setHidden(false)}} className="fixed bottom-4 right-4 z-[80] rounded-full border border-violet-400/30 bg-[#090a14]/90 px-3 py-2 text-xs font-bold text-violet-200 shadow-2xl backdrop-blur-xl">AI Asistanı Göster</button>;
 const score=context?.latestAdvisor?.analysis?.overallScore;const net=context?.cashflow?.net;
 return <div className="fixed bottom-5 right-5 z-[80] flex items-end gap-3">{(open||notice)&&<div className="mb-3 w-[320px] overflow-hidden rounded-2xl border border-violet-400/20 bg-[#080914]/94 shadow-[0_24px_80px_rgba(30,10,70,.52)] backdrop-blur-2xl"><div className="border-b border-white/10 bg-gradient-to-r from-violet-600/18 to-indigo-500/5 px-4 py-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-300">BrandFlow AI</p><p className="mt-1 text-sm font-bold text-white">İş ortağın hazır.</p></div><button onClick={()=>{setNotice(false);setOpen(false)}} className="text-zinc-500 transition hover:text-white" aria-label="Kapat">×</button></div></div><div className="space-y-3 p-4"><p className="text-sm leading-6 text-zinc-300">Bulunduğun sayfayı ve BrandFlow iç verilerini birlikte değerlendirip sana uygulanabilir sonraki adımı gösterebilirim.</p>{open&&<div className="grid grid-cols-3 gap-2"><div className="rounded-xl bg-white/[.04] p-2 text-center"><p className="text-[10px] text-zinc-500">Medya</p><p className="mt-1 text-sm font-black text-white">{context?.mediaCount??"—"}</p></div><div className="rounded-xl bg-white/[.04] p-2 text-center"><p className="text-[10px] text-zinc-500">Plan</p><p className="mt-1 text-sm font-black text-white">{context?.scheduledCount??"—"}</p></div><div className="rounded-xl bg-white/[.04] p-2 text-center"><p className="text-[10px] text-zinc-500">Skor</p><p className="mt-1 text-sm font-black text-white">{score??"—"}</p></div></div>}{open&&typeof net==="number"&&<div className={`rounded-xl border px-3 py-2 text-xs ${net>=0?"border-emerald-400/15 bg-emerald-400/[.06] text-emerald-200":"border-amber-400/15 bg-amber-400/[.06] text-amber-200"}`}>Hesap akışı neti: {new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(net)}</div>}<div className="grid gap-2"><Link href="/company-doctor" className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm font-semibold text-white transition hover:border-violet-400/35 hover:bg-violet-500/10">Şirketimi analiz et</Link><Link href="/opportunities" className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm font-semibold text-white transition hover:border-violet-400/35 hover:bg-violet-500/10">Yeni fırsatları göster</Link><Link href="/create" className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm font-semibold text-white transition hover:border-violet-400/35 hover:bg-violet-500/10">Bugün ne paylaşmalıyım?</Link></div><p className="text-[11px] text-zinc-500">Asistanı yaklaşık 1 saniye basılı tutarak gizleyebilirsin.</p></div></div>}
 <button type="button" onClick={()=>{setOpen(v=>!v);setNotice(false)}} onPointerDown={startHold} onPointerUp={stopHold} onPointerLeave={stopHold} onPointerCancel={stopHold} className="group relative h-[78px] w-[62px] select-none rounded-[20px] border border-violet-400/25 bg-gradient-to-b from-[#151629]/95 to-[#05060b]/95 shadow-[0_18px_60px_rgba(90,45,190,.38)] backdrop-blur-xl transition hover:-translate-y-1 hover:border-violet-300/45" aria-label="BrandFlow AI Asistan"><span className="absolute left-1/2 top-[8px] h-[27px] w-[25px] -translate-x-1/2 rounded-[48%_48%_44%_44%] bg-gradient-to-br from-zinc-400 via-zinc-600 to-zinc-900 shadow-[inset_-3px_-4px_7px_rgba(0,0,0,.45)]"/><span className="absolute left-1/2 top-[7px] h-[9px] w-[25px] -translate-x-1/2 rounded-t-full bg-[#05060a]"/><span className="absolute left-[21px] top-[20px] h-[3px] w-[3px] rounded-full bg-violet-200 shadow-[0_0_9px_#c4b5fd]"/><span className="absolute right-[21px] top-[20px] h-[3px] w-[3px] rounded-full bg-violet-200 shadow-[0_0_9px_#c4b5fd]"/><span className="absolute bottom-[7px] left-1/2 h-[38px] w-[43px] -translate-x-1/2 rounded-[9px_9px_13px_13px] bg-gradient-to-br from-[#17182b] to-[#03040a] shadow-[inset_0_0_0_1px_rgba(255,255,255,.08)]"/><span className="absolute bottom-[8px] left-1/2 h-[28px] w-[2px] -translate-x-1/2 bg-violet-500/70"/><span className="absolute bottom-[25px] left-1/2 h-0 w-0 -translate-x-1/2 border-l-[5px] border-r-[5px] border-t-[9px] border-l-transparent border-r-transparent border-t-violet-500"/><span className="absolute -right-1 -top-1 h-3 w-3 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]"/></button></div>
}
