"use client";

import { useEffect,useMemo,useState } from "react";

type Entry={id:string;entry_type:"income"|"expense";category:string;title:string;amount:number;entry_date:string;note:string};
const categories=["Satış","Hizmet","Reklam","Abonelik","Ekip","Araçlar","İş Birliği","Diğer"];
const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:2});

export default function CashFlowClient(){
 const[entries,setEntries]=useState<Entry[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 const[form,setForm]=useState({entryType:"income" as "income"|"expense",category:"Satış",title:"",amount:"",entryDate:new Date().toISOString().slice(0,10),note:""});
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/cashflow");const j=await r.json();if(!r.ok)throw new Error(j.error||"Yüklenemedi");setEntries(j.data||[])}catch(e){setError(e instanceof Error?e.message:"Yüklenemedi")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const totals=useMemo(()=>{let income=0,expense=0;for(const e of entries){if(e.entry_type==="income")income+=Number(e.amount);else expense+=Number(e.amount)}return{income,expense,net:income-expense}},[entries]);
 async function add(){if(!form.title.trim()||!form.amount)return;setSaving(true);setError("");try{const r=await fetch("/api/cashflow",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Kaydedilemedi");setEntries(c=>[j.data,...c]);setForm(c=>({...c,title:"",amount:"",note:""}))}catch(e){setError(e instanceof Error?e.message:"Kaydedilemedi")}finally{setSaving(false)}}
 async function remove(id:string){const r=await fetch(`/api/cashflow?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setEntries(c=>c.filter(x=>x.id!==id))}
 return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3">{[["Toplam Gelir",totals.income,"text-emerald-300"],["Toplam Gider",totals.expense,"text-rose-300"],["Net Akış",totals.net,totals.net>=0?"text-cyan-300":"text-amber-300"]].map(([l,v,c])=><div key={String(l)} className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-5 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.16em] text-zinc-500">{l}</p><p className={`mt-3 text-3xl font-black ${c}`}>{money.format(Number(v))}</p></div>)}</div>
 <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><h2 className="text-lg font-black">Yeni kayıt</h2><div className="mt-5 grid gap-3"><div className="grid grid-cols-2 gap-2"><button onClick={()=>setForm(c=>({...c,entryType:"income"}))} className={`rounded-xl px-3 py-2 text-sm font-black ${form.entryType==="income"?"bg-emerald-500/20 text-emerald-200 ring-1 ring-emerald-400/30":"bg-white/[.04] text-zinc-400"}`}>Gelir</button><button onClick={()=>setForm(c=>({...c,entryType:"expense"}))} className={`rounded-xl px-3 py-2 text-sm font-black ${form.entryType==="expense"?"bg-rose-500/20 text-rose-200 ring-1 ring-rose-400/30":"bg-white/[.04] text-zinc-400"}`}>Gider</button></div><select value={form.category} onChange={e=>setForm(c=>({...c,category:e.target.value}))} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white">{categories.map(x=><option key={x}>{x}</option>)}</select><input value={form.title} onChange={e=>setForm(c=>({...c,title:e.target.value}))} placeholder="Açıklama" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-violet-400/50"/><input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm(c=>({...c,amount:e.target.value}))} placeholder="Tutar (₺)" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-violet-400/50"/><input type="date" value={form.entryDate} onChange={e=>setForm(c=>({...c,entryDate:e.target.value}))} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white"/><textarea value={form.note} onChange={e=>setForm(c=>({...c,note:e.target.value}))} placeholder="Not (isteğe bağlı)" rows={3} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-violet-400/50"/><button disabled={saving} onClick={add} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{saving?"Kaydediliyor…":"Kaydet"}</button>{error&&<p className="text-sm text-rose-300">{error}</p>}</div></div>
 <div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Son hareketler</h2><span className="text-xs text-zinc-500">{entries.length} kayıt</span></div><div className="mt-4 space-y-2">{loading?<div className="h-24 animate-pulse rounded-2xl bg-white/5"/>:entries.length===0?<p className="text-sm text-zinc-500">Henüz gelir veya gider eklenmedi.</p>:entries.slice(0,30).map(e=><div key={e.id} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${e.entry_type==="income"?"bg-emerald-400":"bg-rose-400"}`}/><p className="truncate font-bold text-white">{e.title}</p></div><p className="mt-1 text-xs text-zinc-500">{e.category} · {new Date(`${e.entry_date}T12:00:00`).toLocaleDateString("tr-TR")}</p></div><div className="flex items-center gap-3"><p className={`font-black ${e.entry_type==="income"?"text-emerald-300":"text-rose-300"}`}>{e.entry_type==="income"?"+":"-"}{money.format(Number(e.amount))}</p><button onClick={()=>remove(e.id)} className="text-xs text-zinc-600 hover:text-rose-300">Sil</button></div></div>)}</div></div></div></div>
}
