"use client";

import type { DragEvent } from "react";
import { useEffect,useMemo,useRef,useState } from "react";
import { Button,Card,EmptyState,Modal,SearchInput } from "@/components/ui";
import type { MediaAsset,MediaAssetType } from "@/lib/media/types";

type SortOption="newest"|"oldest"|"largest"|"smallest";
type FilterOption="all"|MediaAssetType;
type QueueStatus="ready"|"uploading"|"success"|"error"|"invalid";
type QueueItem={id:string;file:File;type:MediaAssetType;status:QueueStatus;progress:number;error:string;previewUrl:string};
type UploadResponse={data?:{media:MediaAsset;upload:{signedUrl:string;path:string;token?:string}};error?:string};

const IMAGE_LIMIT=8*1024*1024;
const VIDEO_LIMIT=100*1024*1024;
const IMAGE_MIMES=new Set(["image/jpeg","image/png","image/webp"]);
const VIDEO_MIMES=new Set(["video/mp4","video/webm","video/quicktime"]);
const signedUrlCache=new Map<string,string>();
const signedUrlFailures=new Set<string>();

function formatBytes(bytes:number){if(!bytes)return"0 B";const units=["B","KB","MB","GB"];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);const value=bytes/1024**i;return`${value.toFixed(value>=10||i===0?0:1)} ${units[i]}`}
function formatDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?"-":d.toLocaleDateString("tr-TR")}
function inferType(file:File):MediaAssetType{return VIDEO_MIMES.has(file.type)?"video":"image"}
function validate(file:File,type:MediaAssetType){if((type==="image"||type==="logo")&&!IMAGE_MIMES.has(file.type))return"Bu görsel desteklenmiyor. JPG, PNG veya WEBP seç.";if(type==="video"&&!VIDEO_MIMES.has(file.type))return"Bu video desteklenmiyor. MP4, WEBM veya MOV seç.";if(file.size<=0)return"Dosya boş görünüyor.";if(file.size>(type==="video"?VIDEO_LIMIT:IMAGE_LIMIT))return`${type==="video"?"Video 100 MB":"Görsel 8 MB"} sınırını aşıyor.`;return""}

async function putSignedFile(file:File,signedUrl:string,onProgress:(p:number)=>void){return new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();const body=new FormData();body.append("cacheControl","3600");body.append("",file);xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.min(95,Math.max(5,Math.round(e.loaded/e.total*95))))};xhr.onload=()=>xhr.status>=200&&xhr.status<300?(onProgress(100),resolve()):reject(new Error(`Dosya depoya gönderilemedi (${xhr.status}).`));xhr.onerror=()=>reject(new Error("Depolama bağlantısı kurulamadı. İnternetini kontrol edip tekrar dene."));xhr.onabort=()=>reject(new Error("Yükleme iptal edildi."));xhr.open("PUT",signedUrl);xhr.setRequestHeader("x-upsert","false");xhr.send(body)})}

async function signedUrlFor(item:MediaAsset){if(!item.storagePath)throw new Error("Bu kayıt için dosya yolu bulunmuyor. Eski veya eksik bir medya kaydı olabilir.");const cached=signedUrlCache.get(item.id);if(cached)return cached;if(signedUrlFailures.has(item.id))throw new Error("Dosya depoda bulunamadı. Kaydı silebilir veya dosyayı yeniden yükleyebilirsin.");const r=await fetch(`/api/media/${item.id}/signed-url`,{method:"POST"});const j=await r.json() as {data?:{signedUrl?:string};error?:string};if(!r.ok||!j.data?.signedUrl){signedUrlFailures.add(item.id);throw new Error(r.status===404?"Dosya depoda bulunamadı. Bu eski kaydı silip yeniden yükleyebilirsin.":j.error||"Önizleme açılamadı.")}signedUrlCache.set(item.id,j.data.signedUrl);return j.data.signedUrl}

export function MediaCenterClient(){
 const[items,setItems]=useState<MediaAsset[]>([]);const[filter,setFilter]=useState<FilterOption>("all");const[search,setSearch]=useState("");const[sort,setSort]=useState<SortOption>("newest");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[queue,setQueue]=useState<QueueItem[]>([]);const[uploading,setUploading]=useState(false);const[imageType,setImageType]=useState<"image"|"logo">("image");const[dragging,setDragging]=useState(false);const[success,setSuccess]=useState("");const[preview,setPreview]=useState<{item:MediaAsset;url:string}|null>(null);const[previewError,setPreviewError]=useState("");const inputRef=useRef<HTMLInputElement|null>(null);const queueRef=useRef<QueueItem[]>([]);
 useEffect(()=>{queueRef.current=queue},[queue]);
 useEffect(()=>()=>{queueRef.current.forEach(q=>URL.revokeObjectURL(q.previewUrl))},[]);

 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/media?sort=newest",{cache:"no-store"});const j=await r.json() as {data?:MediaAsset[];error?:string};if(!r.ok||!Array.isArray(j.data))throw new Error(j.error||"Medya listesi alınamadı.");setItems(j.data)}catch(e){setError(e instanceof Error?e.message:"Medya listesi alınamadı. Sayfayı yenileyip tekrar dene.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);

 const visible=useMemo(()=>{let out=[...items];if(filter!=="all")out=out.filter(x=>x.type===filter);if(search.trim())out=out.filter(x=>x.name.toLocaleLowerCase("tr").includes(search.trim().toLocaleLowerCase("tr")));out.sort((a,b)=>sort==="oldest"?+new Date(a.createdAt)-+new Date(b.createdAt):sort==="largest"?b.size-a.size:sort==="smallest"?a.size-b.size:+new Date(b.createdAt)-+new Date(a.createdAt));return out},[items,filter,search,sort]);
 const stats=useMemo(()=>({total:items.length,images:items.filter(x=>x.type==="image").length,videos:items.filter(x=>x.type==="video").length,logos:items.filter(x=>x.type==="logo").length,space:items.reduce((a,b)=>a+b.size,0)}),[items]);

 function addFiles(files:FileList|File[]){const next=Array.from(files).map(file=>{const inferred=inferType(file);const type=inferred==="video"?"video":imageType;const message=validate(file,type);return{id:crypto.randomUUID(),file,type,status:message?"invalid":"ready",progress:0,error:message,previewUrl:URL.createObjectURL(file)} satisfies QueueItem});setQueue(q=>[...q,...next]);setSuccess("");setError("");if(inputRef.current)inputRef.current.value=""}
 function drop(e:DragEvent<HTMLLabelElement>){e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files)}
 function patch(id:string,data:Partial<QueueItem>){setQueue(q=>q.map(x=>x.id===id?{...x,...data}:x))}
 function clear(){queue.forEach(q=>URL.revokeObjectURL(q.previewUrl));setQueue([]);setSuccess("")}
 function removeQueued(id:string){setQueue(q=>{const item=q.find(x=>x.id===id);if(item)URL.revokeObjectURL(item.previewUrl);return q.filter(x=>x.id!==id)})}

 async function uploadOne(item:QueueItem){let mediaId="";try{patch(item.id,{status:"uploading",progress:3,error:""});const r=await fetch("/api/media/upload-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filename:item.file.name,mimeType:item.file.type,size:item.file.size,type:item.type})});const j=await r.json() as UploadResponse;if(!r.ok||!j.data?.upload?.signedUrl)throw new Error(j.error||"Yükleme bağlantısı oluşturulamadı. Depolama ayarları eksik olabilir.");mediaId=j.data.media.id;await putSignedFile(item.file,j.data.upload.signedUrl,p=>patch(item.id,{progress:p,status:"uploading"}));patch(item.id,{status:"success",progress:100});return true}catch(e){if(mediaId)await fetch(`/api/media/${mediaId}`,{method:"DELETE"}).catch(()=>undefined);patch(item.id,{status:"error",progress:0,error:e instanceof Error?e.message:"Yükleme başarısız. Tekrar deneyebilirsin."});return false}}
 async function uploadAll(){if(uploading)return;const pending=queue.filter(x=>x.status==="ready"||x.status==="error");if(!pending.length)return;setUploading(true);setError("");setSuccess("");let count=0;for(const item of pending){if(await uploadOne(item))count++}setUploading(false);if(count){setSuccess(`${count} dosya başarıyla yüklendi ve Medya Merkezi'ne eklendi.`);await load()}}

 async function openPreview(item:MediaAsset){setPreviewError("");try{const url=await signedUrlFor(item);setPreview({item,url})}catch(e){setPreview(null);setPreviewError(e instanceof Error?e.message:"Önizleme açılamadı.")}}
 async function rename(item:MediaAsset){const name=window.prompt("Yeni medya adı",item.name)?.trim();if(!name||name===item.name)return;const r=await fetch(`/api/media/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});const j=await r.json() as {data?:MediaAsset;error?:string};if(!r.ok||!j.data){setError(j.error||"Dosyanın adı değiştirilemedi.");return}setItems(x=>x.map(v=>v.id===item.id?j.data!:v))}
 async function remove(item:MediaAsset){if(!window.confirm(`${item.name} silinsin mi?`))return;const r=await fetch(`/api/media/${item.id}`,{method:"DELETE"});if(!r.ok){setError("Dosya silinemedi. Tekrar deneyebilirsin.");return}signedUrlCache.delete(item.id);signedUrlFailures.delete(item.id);setItems(x=>x.filter(v=>v.id!==item.id));setSuccess("Dosya Medya Merkezi'nden kaldırıldı.")}

 const readyCount=queue.filter(x=>x.status==="ready"||x.status==="error").length;
 return <div className="space-y-5">
  <Modal title={preview?.item.name||"Medya önizleme"} open={Boolean(preview)||Boolean(previewError)} onClose={()=>{setPreview(null);setPreviewError("")}}>{previewError?<div className="rounded-xl border border-amber-400/25 bg-amber-400/10 p-4"><p className="font-bold text-amber-100">Bu dosya açılamadı.</p><p className="mt-2 text-sm leading-6 text-amber-100/80">{previewError}</p></div>:preview?.item.type==="video"?<video src={preview.url} controls playsInline className="max-h-[70vh] w-full rounded-xl bg-black object-contain"/>:preview?<img src={preview.url} alt={preview.item.name} className="max-h-[70vh] w-full rounded-xl bg-black object-contain"/>:null}</Modal>

  <Card className="p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">1 · Dosyanı seç</p><h2 className="mt-1 text-lg font-black text-white">Medya yükle</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">Dosyayı seç → önizlemeyi kontrol et → <b className="text-zinc-300">Seçilenleri yükle</b>. Görsel/logo en fazla 8 MB, video en fazla 100 MB.</p></div><label className="text-xs font-semibold text-zinc-300">Görseli nasıl kaydedelim?<select value={imageType} onChange={e=>setImageType(e.target.value as "image"|"logo")} className="mt-2 block rounded-lg border border-white/10 bg-zinc-950 px-3 py-2 text-sm"><option value="image">Görsel</option><option value="logo">Logo</option></select></label></div>
   <label htmlFor="mediaUpload" onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`mt-5 flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed p-6 text-center transition ${dragging?"border-emerald-300 bg-emerald-400/10":"border-white/15 bg-black/25 hover:border-emerald-400/30"}`}><input ref={inputRef} id="mediaUpload" type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" className="sr-only" onChange={e=>e.target.files&&addFiles(e.target.files)}/><b>Dosyaları buraya bırak</b><span className="mt-2 text-sm text-zinc-500">veya bilgisayarından seç</span><span className="mt-4 rounded-lg bg-emerald-400 px-4 py-2 text-sm font-black text-zinc-950">Dosya Seç</span></label>

   {queue.length>0&&<div className="mt-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-zinc-500">2 · Kontrol et ve yükle</p><p className="mt-1 text-sm text-zinc-400">{readyCount>0?`${readyCount} dosya yüklenmeye hazır.`:"Seçili dosyalar işlendi."}</p></div><div className="flex gap-2"><Button onClick={uploadAll} disabled={uploading||readyCount===0}>{uploading?"Yükleniyor...":"Seçilenleri yükle"}</Button><Button variant="secondary" onClick={clear} disabled={uploading}>Listeyi temizle</Button></div></div>{queue.map(q=><div key={q.id} className="grid gap-3 rounded-xl border border-white/10 bg-black/30 p-3 md:grid-cols-[72px_1fr_120px] md:items-center"><div className="h-16 w-16 overflow-hidden rounded-lg border border-white/10">{q.type==="video"?<video src={q.previewUrl} muted className="h-full w-full object-cover"/>:<img src={q.previewUrl} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><b className="block truncate text-sm">{q.file.name}</b><p className="mt-1 text-xs text-zinc-500">{formatBytes(q.file.size)} · {q.type==="video"?"Video":q.type==="logo"?"Logo":"Görsel"}</p></div><button type="button" disabled={uploading} onClick={()=>removeQueued(q.id)} className="text-xs font-bold text-zinc-500 hover:text-red-200">Kaldır</button></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-zinc-800"><div className={`h-full transition-all ${q.status==="error"||q.status==="invalid"?"bg-red-400":"bg-emerald-400"}`} style={{width:`${q.status==="invalid"?100:q.progress}%`}}/></div>{q.error&&<p className="mt-2 text-xs font-semibold leading-5 text-red-200">{q.error}</p>}</div><div className="text-right"><p className="text-xs font-bold text-zinc-400">{q.status==="ready"?"Hazır":q.status==="uploading"?"Yükleniyor":q.status==="success"?"Tamamlandı":q.status==="invalid"?"Düzeltmen gerek":"Tekrar deneyebilirsin"}</p><p className="mt-1 text-lg font-black">{q.status==="invalid"?"—":`${q.progress}%`}</p></div></div>)}</div>}
   {success&&<p className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm font-bold text-emerald-200">{success}</p>}
  </Card>

  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[["Toplam medya",stats.total],["Görseller",stats.images],["Videolar",stats.videos],["Logolar",stats.logos],["Kullanılan alan",formatBytes(stats.space)]].map(([k,v])=><Card key={String(k)} className="p-4"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">{k}</p><p className="mt-2 text-2xl font-black text-white">{v}</p></Card>)}</div>

  <Card className="p-4"><div className="grid gap-3 lg:grid-cols-[1fr_220px]"><SearchInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Dosya adına göre ara..."/><select value={sort} onChange={e=>setSort(e.target.value as SortOption)} className="rounded-lg border border-white/10 bg-zinc-950 px-4 py-3"><option value="newest">En yeni</option><option value="oldest">En eski</option><option value="largest">En büyük</option><option value="smallest">En küçük</option></select></div><div className="mt-4 flex flex-wrap gap-2">{([['all','Tümü'],['image','Görseller'],['video','Videolar'],['logo','Logolar']] as Array<[FilterOption,string]>).map(([v,l])=><button type="button" key={v} onClick={()=>setFilter(v)} className={`rounded-lg border px-3 py-2 text-sm font-bold ${filter===v?"border-emerald-400/40 bg-emerald-400/10 text-emerald-100":"border-white/10 text-zinc-400"}`}>{l}</button>)}</div></Card>
  {error?<Card className="border-red-400/30 bg-red-500/10 p-5"><p className="font-bold text-red-100">Bir şey ters gitti.</p><p className="mt-2 text-sm leading-6 text-red-200/80">{error}</p><button type="button" onClick={()=>void load()} className="mt-3 rounded-lg border border-red-300/20 px-3 py-2 text-xs font-black text-red-100">Tekrar dene</button></Card>:loading?<Card className="p-10 text-center text-zinc-400">Medya yükleniyor...</Card>:visible.length===0?<EmptyState title="Medya bulunamadı" description="Dosya yükleyebilir veya filtreyi değiştirebilirsin."/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visible.map(item=><MediaCard key={item.id} item={item} onOpen={openPreview} onRename={rename} onDelete={remove}/>)}</div>}
 </div>
}

function MediaCard({item,onOpen,onRename,onDelete}:{item:MediaAsset;onOpen:(i:MediaAsset)=>void;onRename:(i:MediaAsset)=>void;onDelete:(i:MediaAsset)=>void}){
 const[url,setUrl]=useState(()=>signedUrlCache.get(item.id)||"");const[broken,setBroken]=useState(signedUrlFailures.has(item.id));const rootRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(url||broken||!item.storagePath)return;const node=rootRef.current;if(!node)return;let active=true;const observer=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting))return;observer.disconnect();void signedUrlFor(item).then(value=>{if(active)setUrl(value)}).catch(()=>{if(active)setBroken(true)})},{rootMargin:"250px"});observer.observe(node);return()=>{active=false;observer.disconnect()}},[item,url,broken]);
 return <div ref={rootRef}><Card className="overflow-hidden"><button type="button" className="grid h-44 w-full place-items-center overflow-hidden bg-black/40" onClick={()=>onOpen(item)}>{broken?<div className="px-5 text-center"><p className="text-xs font-black text-amber-200">Dosya bulunamadı</p><p className="mt-1 text-[11px] leading-4 text-zinc-500">Kayıt var ama dosya depoda yok. Silip yeniden yükleyebilirsin.</p></div>:url&&item.type==="video"?<video src={url} muted playsInline className="h-full w-full object-cover"/>:url?<img src={url} alt={item.name} className="h-full w-full object-cover"/>:<div className="text-center"><span className="text-xs font-black text-emerald-200">{item.type.toUpperCase()}</span><p className="mt-2 text-[11px] text-zinc-600">Önizleme yükleniyor...</p></div>}</button><div className="p-4"><div className="flex items-start justify-between gap-3"><b className="truncate">{item.name}</b><span className="rounded-full border border-white/10 px-2 py-1 text-xs text-zinc-400">{item.type==="image"?"Görsel":item.type==="video"?"Video":"Logo"}</span></div><p className="mt-3 text-xs text-zinc-500">{formatBytes(item.size)} · {formatDate(item.createdAt)}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>onOpen(item)} className="rounded-lg border border-violet-400/20 bg-violet-500/10 px-3 py-2 text-xs font-bold text-violet-100">Aç</button><button type="button" onClick={()=>onRename(item)} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold">Adını değiştir</button><button type="button" onClick={()=>onDelete(item)} className="rounded-lg border border-red-400/30 px-3 py-2 text-xs font-bold text-red-200">Sil</button></div></div></Card></div>
}
