"use client";

import Image from "next/image";
import { useState } from "react";
import { Button, Card, EmptyState, Modal } from "@/components/ui";
import type { MediaAsset } from "@/lib/media/types";
import type { ScheduledPublish } from "@/lib/scheduling/types";

const labels = { scheduled: "Planlandı", processing: "İşleniyor", published: "Yayınlandı", failed: "Başarısız", cancelled: "İptal" } as const;
const styles = { scheduled: "bg-sky-400/10 text-sky-200", processing: "bg-amber-400/10 text-amber-200", published: "bg-emerald-400/10 text-emerald-200", failed: "bg-red-400/10 text-red-200", cancelled: "bg-zinc-500/10 text-zinc-400" } as const;
function localInput(value: string) { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function tags(value: string) { return Array.from(new Set(value.match(/#[A-Za-z0-9_ğüşıöçİĞÜŞÖÇ]+/g) || [])).slice(0, 30); }

export function QueueClient({ initialItems, mediaAssets, initialError }: { initialItems: ScheduledPublish[]; mediaAssets: MediaAsset[]; initialError: string }) {
  const [items, setItems] = useState(initialItems); const [error, setError] = useState(initialError); const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<ScheduledPublish | null>(null); const [busyId, setBusyId] = useState("");
  const [caption, setCaption] = useState(""); const [mediaId, setMediaId] = useState(""); const [scheduledAt, setScheduledAt] = useState(""); const [timezone, setTimezone] = useState("");
  const media = mediaAssets.filter((item) => item.type === "image" || item.type === "logo");
  const active = items.filter((item) => !["published", "cancelled"].includes(item.status)); const completed = items.filter((item) => ["published", "cancelled"].includes(item.status));

  async function reload() { const response = await fetch("/api/scheduled-publishes", { cache: "no-store" }); const json = await response.json() as { data?: ScheduledPublish[]; error?: string }; if (!response.ok || !json.data) throw new Error(json.error || "Kuyruk yenilenemedi."); setItems(json.data); }
  function edit(item: ScheduledPublish) { setSelected(item); setCaption(item.caption); setMediaId(item.mediaAssetId); setScheduledAt(localInput(item.scheduledAt)); setTimezone(item.timezone); setError(""); }
  async function update() { if (!selected) return; setBusyId(selected.id); try { const response = await fetch(`/api/scheduled-publishes/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profileId: selected.profileId, mediaAssetId: mediaId, platforms: selected.platforms, title: caption.split(/\r?\n/)[0], caption, hashtags: tags(caption), platformContent: selected.platformContent, scheduledAt: new Date(scheduledAt).toISOString(), timezone }) }); const json = await response.json() as { data?: ScheduledPublish; error?: string }; if (!response.ok || !json.data) throw new Error(json.error || "Plan güncellenemedi."); await reload(); setSelected(null); setNotice("Plan güncellendi."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Plan güncellenemedi."); } finally { setBusyId(""); } }
  async function publish(item: ScheduledPublish) { setBusyId(item.id); setError(""); setNotice(""); try { const response = await fetch(`/api/scheduled-publishes/${item.id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ retry: item.status === "failed" }) }); const json = await response.json() as { data?: unknown; error?: string; code?: string }; await reload(); if (!response.ok) throw new Error(json.code === "connection_expired" ? "Instagram bağlantısının süresi dolmuş. Bağlantılar ekranından yeniden bağla." : json.error || "Paylaşım tamamlanamadı."); setNotice("Paylaşım başarıyla yayınlandı."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Paylaşım tamamlanamadı."); } finally { setBusyId(""); } }
  async function cancel(item: ScheduledPublish) { if (!window.confirm("Bu planı iptal etmek istediğine emin misin?")) return; setBusyId(item.id); const response = await fetch(`/api/scheduled-publishes/${item.id}`, { method: "DELETE" }); setBusyId(""); if (!response.ok) { const json = await response.json() as { error?: string }; return setError(json.error || "Plan iptal edilemedi."); } await reload(); setNotice("Plan iptal edildi."); }

  function list(itemsToShow: ScheduledPublish[]) { return <div className="grid gap-3">{itemsToShow.map((item) => <Card key={item.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="relative grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-md bg-zinc-950 text-xs text-zinc-500">{item.media?.signedUrl ? <Image src={item.media.signedUrl} alt={item.media.name} fill unoptimized className="object-cover" /> : "MEDYA"}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="rounded bg-white/10 px-2 py-1 text-[11px] font-bold">Instagram</span><span className={`rounded px-2 py-1 text-[11px] font-bold ${styles[item.status]}`}>{labels[item.status]}</span></div><p className="mt-2 truncate text-sm font-semibold">{item.caption.split(/\r?\n/)[0]}</p><p className="mt-1 text-xs text-zinc-500">{item.accountUsername ? `@${item.accountUsername.replace(/^@/, "")}` : item.accountName || "Instagram"} · {new Date(item.scheduledAt).toLocaleString("tr-TR", { timeZone: item.timezone })}</p>{item.lastError ? <p className="mt-1 line-clamp-1 text-xs text-red-300">{item.lastError}</p> : null}</div>{["scheduled", "failed"].includes(item.status) ? <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => edit(item)}>Düzenle</Button><Button onClick={() => void publish(item)} disabled={busyId === item.id}>{item.status === "failed" ? "Tekrar Dene" : "Şimdi Yayınla"}</Button><Button variant="ghost" onClick={() => void cancel(item)} disabled={busyId === item.id}>İptal Et</Button></div> : null}</Card>)}</div>; }

  return <div className="space-y-7">{error ? <p className="rounded-md border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p> : null}{notice ? <p className="rounded-md border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm text-emerald-200">{notice}</p> : null}<section><h2 className="mb-3 text-lg font-black">Aktif Kuyruk</h2>{active.length ? list(active) : <EmptyState title="Aktif plan yok" description="Paylaşım Merkezi'nden tarih ve saat seçerek ilk paylaşımını planlayabilirsin." />}</section>{completed.length ? <section><h2 className="mb-3 text-lg font-black">Tamamlananlar</h2>{list(completed)}</section> : null}<Modal title="Planı Düzenle" open={Boolean(selected)} onClose={() => setSelected(null)}>{selected ? <div className="space-y-4"><label className="block text-sm font-semibold">Caption<textarea value={caption} onChange={(event) => setCaption(event.target.value)} rows={6} className="mt-2 w-full rounded-md border border-white/10 bg-zinc-950 p-3" /></label><label className="block text-sm font-semibold">Medya<select value={mediaId} onChange={(event) => setMediaId(event.target.value)} className="mt-2 w-full rounded-md border border-white/10 bg-zinc-950 p-3">{media.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-semibold">Tarih ve saat<input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} className="mt-2 w-full rounded-md border border-white/10 bg-zinc-950 p-3" /></label><label className="block text-sm font-semibold">Timezone<input value={timezone} onChange={(event) => setTimezone(event.target.value)} className="mt-2 w-full rounded-md border border-white/10 bg-zinc-950 p-3" /></label><Button onClick={() => void update()} disabled={busyId === selected.id}>Güncelle</Button></div> : null}</Modal></div>;
}
