"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";

type Category={score:number;explanation:string;suggestions:string[]};
type Analysis={overallScore:number;categories:Record<string,Category>;suggestedCampaignObjective:string;betterPostingTime:string;betterCta:string};
type Report={id:string;platform:string;analysis:Analysis};
const labels:Record<string,string>={visualQuality:"Görsel kalite",brandConsistency:"Marka tutarlılığı",audienceMatch:"Hedef kitle uyumu",engagementPrediction:"Etkileşim potansiyeli",ctaStrength:"CTA gücü",captionQuality:"Metin kalitesi",hashtagQuality:"Hashtag kalitesi",platformOptimization:"Platform uyumu",accessibility:"Erişilebilirlik",readingDifficulty:"Okunabilirlik",colorHarmony:"Renk uyumu",composition:"Kompozisyon",textReadability:"Metin okunabilirliği"};

export default function CompanyDoctorClient(){
 const[reports,setReports]=useState<Report[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;fetch("/api/marketing-advisor/analyze?limit=6").then(r=>r.ok?r.json():null).then(j=>{if(active&&Array.isArray(j?.data))setReports(j.data)}).catch(()=>undefined).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const latest=reports[0];const diagnostic=useMemo(()=>{const entries=Object.entries(latest?.analysis?.categories||{}).sort((a,b)=>a[1].score-b[1].score);const risks=entries.slice(0,4).map(([key,c])=>({title:labels[key]||key,score:c.score,text:c.explanation}));const strengths=[...entries].reverse().slice(0,4).map(([key,c])=>({title:labels[key]||key,score:c.score,text:c.explanation}));const actions=entries.flatMap(([key,c])=>(c.suggestions||[]).map(s=>`${labels[key]||key}: ${s}`)).filter(Boolean).slice(0,5);if(latest?.analysis?.betterPostingTime)actions.push(`Paylaşım zamanı: ${latest.analysis.betterPostingTime}`);return{risks,strengths,actions:actions.slice(0,6)}},[latest]);
 if(loading)return <div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-44 animate-pulse rounded-3xl border border-white/10 bg-white/[.04]"/>)}</div>;
 if(!latest)return <div className="rounded-3xl border border-white/10 bg-[#070a16]/65 p-8 backdrop-blur-2xl"><h2 className="text-xl font-black">Henüz teşhis yok</h2><p className="mt-2 text-sm text-zinc-400">Önce markan için bir AI pazarlama analizi oluştur. Şirket Doktoru bu kayıtları burada özetleyecek.</p><Link href="/marketing-advisor" className="mt-5 inline-block rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">İlk analizi oluştur</Link></div>;
 return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-[.7fr_1.3fr]"><div className="rounded-3xl border border-violet-400/15 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-violet-300">Marka sağlığı</p><p className="mt-4 text-6xl font-black text-white">{latest.analysis.overallScore}<span className="text-xl text-zinc-500">/100</span></p><p className="mt-3 text-sm text-zinc-400">Son {latest.platform} analizindeki gerçek kategori puanlarından üretilir.</p>{latest.analysis.suggestedCampaignObjective&&<div className="mt-4 rounded-xl border border-violet-400/15 bg-violet-400/[.07] p-3 text-xs leading-5 text-violet-100">Hedef: {latest.analysis.suggestedCampaignObjective}</div>}</div><div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Öne çıkan güçler</p><div className="mt-4 grid gap-2">{diagnostic.strengths.map(x=><div key={x.title} className="rounded-xl border border-emerald-400/10 bg-emerald-400/[.06] px-4 py-3"><div className="flex justify-between gap-3"><p className="text-sm font-black text-zinc-100">{x.title}</p><span className="text-xs font-black text-emerald-300">{x.score}</span></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-zinc-500">{x.text}</p></div>)}</div></div></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Riskler ve eksikler</p><div className="mt-4 space-y-2">{diagnostic.risks.map(x=><div key={x.title} className="rounded-xl border border-amber-400/10 bg-amber-400/[.06] px-4 py-3"><div className="flex justify-between gap-3"><p className="text-sm font-black text-zinc-100">{x.title}</p><span className="text-xs font-black text-amber-300">{x.score}</span></div><p className="mt-1 text-xs leading-5 text-zinc-500">{x.text}</p></div>)}</div></div><div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Önerilen aksiyonlar</p><div className="mt-4 space-y-2">{diagnostic.actions.length?diagnostic.actions.map((x,i)=><div key={`${x}-${i}`} className="rounded-xl border border-cyan-400/10 bg-cyan-400/[.06] px-4 py-3 text-sm text-zinc-200">{x}</div>):<p className="text-sm text-zinc-500">Bu analiz için ek aksiyon önerisi yok.</p>}</div></div></div><div className="flex flex-wrap gap-2"><Link href="/marketing-advisor" className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">Yeni analiz yap</Link><Link href="/analytics" className="rounded-xl border border-white/10 bg-black/25 px-4 py-2.5 text-sm font-bold text-zinc-200">Analizleri aç</Link></div></div>
}
