"use client";

import Link from "next/link";
import { useEffect,useState } from "react";

type Report={id:string;platform:string;analysis:{overallScore:number;strengths?:string[];weaknesses?:string[];recommendations?:string[];suggestedCampaignObjective?:string}};

export default function CompanyDoctorClient(){
 const [reports,setReports]=useState<Report[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;fetch("/api/marketing-advisor/analyze?limit=6").then(r=>r.ok?r.json():null).then(j=>{if(active&&Array.isArray(j?.data))setReports(j.data)}).catch(()=>undefined).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const latest=reports[0];const score=latest?.analysis?.overallScore;
 const risks=(latest?.analysis?.weaknesses||[]).slice(0,4);const actions=(latest?.analysis?.recommendations||[]).slice(0,4);const strengths=(latest?.analysis?.strengths||[]).slice(0,4);
 if(loading)return <div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-44 animate-pulse rounded-3xl border border-white/10 bg-white/[.04]"/>)}</div>;
 if(!latest)return <div className="rounded-3xl border border-white/10 bg-[#070a16]/65 p-8 backdrop-blur-2xl"><h2 className="text-xl font-black">Henüz teşhis yok</h2><p className="mt-2 text-sm text-zinc-400">Önce markan için bir AI pazarlama analizi oluştur. Şirket Doktoru bu kayıtları burada özetleyecek.</p><Link href="/marketing-advisor" className="mt-5 inline-block rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">İlk analizi oluştur</Link></div>;
 return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-[.7fr_1.3fr]"><div className="rounded-3xl border border-violet-400/15 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-violet-300">Marka sağlığı</p><p className="mt-4 text-6xl font-black text-white">{score??"—"}<span className="text-xl text-zinc-500">/100</span></p><p className="mt-3 text-sm text-zinc-400">Son {latest.platform} analizine göre hazırlık skoru.</p></div><div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Öne çıkan güçler</p><div className="mt-4 grid gap-2">{strengths.length?strengths.map(x=><div key={x} className="rounded-xl border border-emerald-400/10 bg-emerald-400/[.06] px-4 py-3 text-sm text-zinc-200">{x}</div>):<p className="text-sm text-zinc-500">Bu raporda güçlü yön verisi yok.</p>}</div></div></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Riskler ve eksikler</p><div className="mt-4 space-y-2">{risks.length?risks.map(x=><div key={x} className="rounded-xl border border-amber-400/10 bg-amber-400/[.06] px-4 py-3 text-sm text-zinc-200">{x}</div>):<p className="text-sm text-zinc-500">Bu raporda risk kaydı yok.</p>}</div></div><div className="rounded-3xl border border-white/10 bg-[#070a16]/70 p-6 backdrop-blur-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Önerilen aksiyonlar</p><div className="mt-4 space-y-2">{actions.length?actions.map(x=><div key={x} className="rounded-xl border border-cyan-400/10 bg-cyan-400/[.06] px-4 py-3 text-sm text-zinc-200">{x}</div>):<p className="text-sm text-zinc-500">Bu raporda aksiyon önerisi yok.</p>}</div></div></div><div className="flex flex-wrap gap-2"><Link href="/marketing-advisor" className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">Yeni analiz yap</Link><Link href="/analytics" className="rounded-xl border border-white/10 bg-black/25 px-4 py-2.5 text-sm font-bold text-zinc-200">Analizleri aç</Link></div></div>
}
